// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file osmosis/txfees/v1beta1/query.proto (package osmosis.txfees.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryBaseDenomRequest, QueryBaseDenomResponse, QueryDenomPoolIdRequest, QueryDenomPoolIdResponse, QueryDenomSpotPriceRequest, QueryDenomSpotPriceResponse, QueryEipBaseFeeRequest, QueryEipBaseFeeResponse, QueryFeeTokensRequest, QueryFeeTokensResponse } from "./query_pb.js";

const TYPE_NAME = "osmosis.txfees.v1beta1.Query";

/**
 * FeeTokens returns a list of all the whitelisted fee tokens and their
 * corresponding pools. It does not include the BaseDenom, which has its own
 * query endpoint
 *
 * @generated from rpc osmosis.txfees.v1beta1.Query.FeeTokens
 */
export const QueryFeeTokensService = {
  typeName: TYPE_NAME,
  method: "FeeTokens",
  Request: QueryFeeTokensRequest,
  Response: QueryFeeTokensResponse,
} as const;

/**
 * DenomSpotPrice returns all spot prices by each registered token denom.
 *
 * @generated from rpc osmosis.txfees.v1beta1.Query.DenomSpotPrice
 */
export const QueryDenomSpotPriceService = {
  typeName: TYPE_NAME,
  method: "DenomSpotPrice",
  Request: QueryDenomSpotPriceRequest,
  Response: QueryDenomSpotPriceResponse,
} as const;

/**
 * Returns the poolID for a specified denom input.
 *
 * @generated from rpc osmosis.txfees.v1beta1.Query.DenomPoolId
 */
export const QueryDenomPoolIdService = {
  typeName: TYPE_NAME,
  method: "DenomPoolId",
  Request: QueryDenomPoolIdRequest,
  Response: QueryDenomPoolIdResponse,
} as const;

/**
 * Returns a list of all base denom tokens and their corresponding pools.
 *
 * @generated from rpc osmosis.txfees.v1beta1.Query.BaseDenom
 */
export const QueryBaseDenomService = {
  typeName: TYPE_NAME,
  method: "BaseDenom",
  Request: QueryBaseDenomRequest,
  Response: QueryBaseDenomResponse,
} as const;

/**
 * Returns a list of all base denom tokens and their corresponding pools.
 *
 * @generated from rpc osmosis.txfees.v1beta1.Query.GetEipBaseFee
 */
export const QueryGetEipBaseFeeService = {
  typeName: TYPE_NAME,
  method: "GetEipBaseFee",
  Request: QueryEipBaseFeeRequest,
  Response: QueryEipBaseFeeResponse,
} as const;

