// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file elys/masterchef/genesis.proto (package elys.masterchef, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { ExternalIncentive } from "./external_incentive_pb.js";
import { PoolInfo, PoolRewardInfo, PoolRewardsAccum, UserRewardInfo } from "./pool_pb.js";

/**
 * GenesisState defines the masterchef module's genesis state.
 *
 * @generated from message elys.masterchef.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: elys.masterchef.Params params = 1;
   */
  params?: Params;

  /**
   * @generated from field: repeated elys.masterchef.ExternalIncentive external_incentives = 2;
   */
  externalIncentives: ExternalIncentive[] = [];

  /**
   * @generated from field: uint64 external_incentive_index = 3;
   */
  externalIncentiveIndex = protoInt64.zero;

  /**
   * @generated from field: repeated elys.masterchef.PoolInfo pool_infos = 4;
   */
  poolInfos: PoolInfo[] = [];

  /**
   * @generated from field: repeated elys.masterchef.PoolRewardInfo pool_reward_infos = 5;
   */
  poolRewardInfos: PoolRewardInfo[] = [];

  /**
   * @generated from field: repeated elys.masterchef.UserRewardInfo user_reward_infos = 6;
   */
  userRewardInfos: UserRewardInfo[] = [];

  /**
   * @generated from field: repeated elys.masterchef.PoolRewardsAccum pool_rewards_accum = 7;
   */
  poolRewardsAccum: PoolRewardsAccum[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.masterchef.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "external_incentives", kind: "message", T: ExternalIncentive, repeated: true },
    { no: 3, name: "external_incentive_index", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 4, name: "pool_infos", kind: "message", T: PoolInfo, repeated: true },
    { no: 5, name: "pool_reward_infos", kind: "message", T: PoolRewardInfo, repeated: true },
    { no: 6, name: "user_reward_infos", kind: "message", T: UserRewardInfo, repeated: true },
    { no: 7, name: "pool_rewards_accum", kind: "message", T: PoolRewardsAccum, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

