// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file elys/incentive/query.proto (package elys.incentive, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAprRequest, QueryAprResponse, QueryAprsRequest, QueryAprsResponse, QueryPoolRewardsRequest, QueryPoolRewardsResponse } from "./query_pb.js";

const TYPE_NAME = "elys.incentive.Query";

/**
 * Calculate APR
 *
 * @generated from rpc elys.incentive.Query.Apr
 */
export const QueryAprService = {
  typeName: TYPE_NAME,
  method: "Apr",
  Request: QueryAprRequest,
  Response: QueryAprResponse,
} as const;

/**
 * Calculate APRs
 *
 * @generated from rpc elys.incentive.Query.Aprs
 */
export const QueryAprsService = {
  typeName: TYPE_NAME,
  method: "Aprs",
  Request: QueryAprsRequest,
  Response: QueryAprsResponse,
} as const;

/**
 * Queries PoolReward items
 *
 * @generated from rpc elys.incentive.Query.PoolRewards
 */
export const QueryPoolRewardsService = {
  typeName: TYPE_NAME,
  method: "PoolRewards",
  Request: QueryPoolRewardsRequest,
  Response: QueryPoolRewardsResponse,
} as const;

