// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file elys/estaking/query.proto (package elys.estaking, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse, QueryRewardsRequest, QueryRewardsResponse } from "./query_pb.js";

const TYPE_NAME = "elys.estaking.Query";

/**
 * Parameters queries the parameters of the module.
 *
 * @generated from rpc elys.estaking.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * Rewards queries the total rewards accrued by a delegation
 *
 * @generated from rpc elys.estaking.Query.Rewards
 */
export const QueryRewardsService = {
  typeName: TYPE_NAME,
  method: "Rewards",
  Request: QueryRewardsRequest,
  Response: QueryRewardsResponse,
} as const;

