// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file elys/estaking/tx.proto (package elys.estaking, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdateParams, MsgUpdateParamsResponse, MsgWithdrawAllRewards, MsgWithdrawAllRewardsResponse, MsgWithdrawElysStakingRewards, MsgWithdrawElysStakingRewardsResponse, MsgWithdrawReward, MsgWithdrawRewardResponse } from "./tx_pb.js";

const TYPE_NAME = "elys.estaking.Msg";

/**
 * UpdateParams defines a governance operation for updating the x/distribution
 * module parameters. The authority is defined in the keeper.
 *
 * @generated from rpc elys.estaking.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * WithdrawReward defines a method to withdraw rewards of delegator from a single validator.
 *
 * @generated from rpc elys.estaking.Msg.WithdrawReward
 */
export const MsgWithdrawRewardService = {
  typeName: TYPE_NAME,
  method: "WithdrawReward",
  Request: MsgWithdrawReward,
  Response: MsgWithdrawRewardResponse,
} as const;

/**
 * WithdrawElysStakingRewards defines a method to withdraw rewards of delegator from all the validators.
 *
 * @generated from rpc elys.estaking.Msg.WithdrawElysStakingRewards
 */
export const MsgWithdrawElysStakingRewardsService = {
  typeName: TYPE_NAME,
  method: "WithdrawElysStakingRewards",
  Request: MsgWithdrawElysStakingRewards,
  Response: MsgWithdrawElysStakingRewardsResponse,
} as const;

/**
 * WithdrawAllRewards defines a method to withdraw rewards of delegator from all the validators and Eden/EdenB commitment.
 *
 * @generated from rpc elys.estaking.Msg.WithdrawAllRewards
 */
export const MsgWithdrawAllRewardsService = {
  typeName: TYPE_NAME,
  method: "WithdrawAllRewards",
  Request: MsgWithdrawAllRewards,
  Response: MsgWithdrawAllRewardsResponse,
} as const;

