// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file pryzm/amm/v1/pending_token_introduction.proto (package pryzm.amm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from message pryzm.amm.v1.PendingTokenIntroduction
 */
export class PendingTokenIntroduction extends Message<PendingTokenIntroduction> {
  /**
   * @generated from field: string asset_id = 1;
   */
  assetId = "";

  /**
   * @generated from field: uint64 target_pool_id = 2;
   */
  targetPoolId = protoInt64.zero;

  /**
   * @generated from field: string token_denom = 3;
   */
  tokenDenom = "";

  /**
   * @generated from field: string token_normalized_weight = 4;
   */
  tokenNormalizedWeight = "";

  /**
   * @generated from field: int64 virtual_balance_interval_millis = 5;
   */
  virtualBalanceIntervalMillis = protoInt64.zero;

  constructor(data?: PartialMessage<PendingTokenIntroduction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "pryzm.amm.v1.PendingTokenIntroduction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "asset_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "target_pool_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "token_denom", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "token_normalized_weight", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "virtual_balance_interval_millis", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PendingTokenIntroduction {
    return new PendingTokenIntroduction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PendingTokenIntroduction {
    return new PendingTokenIntroduction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PendingTokenIntroduction {
    return new PendingTokenIntroduction().fromJsonString(jsonString, options);
  }

  static equals(a: PendingTokenIntroduction | PlainMessage<PendingTokenIntroduction> | undefined, b: PendingTokenIntroduction | PlainMessage<PendingTokenIntroduction> | undefined): boolean {
    return proto3.util.equals(PendingTokenIntroduction, a, b);
  }
}

