// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file pryzm/pgov/v1/tx.proto (package pryzm.pgov.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgRetryVoteTransmit, MsgRetryVoteTransmitResponse, MsgStakePAssets, MsgStakePAssetsResponse, MsgSubmitProposal, MsgSubmitProposalResponse, MsgSubmitVote, MsgSubmitVoteResponse, MsgUnstakePAssets, MsgUnstakePAssetsResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "pryzm.pgov.v1.Msg";

/**
 * @generated from rpc pryzm.pgov.v1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

/**
 * @generated from rpc pryzm.pgov.v1.Msg.StakePAssets
 */
export const MsgStakePAssetsService = {
  typeName: TYPE_NAME,
  method: "StakePAssets",
  Request: MsgStakePAssets,
  Response: MsgStakePAssetsResponse,
} as const;

/**
 * @generated from rpc pryzm.pgov.v1.Msg.UnstakePAssets
 */
export const MsgUnstakePAssetsService = {
  typeName: TYPE_NAME,
  method: "UnstakePAssets",
  Request: MsgUnstakePAssets,
  Response: MsgUnstakePAssetsResponse,
} as const;

/**
 * @generated from rpc pryzm.pgov.v1.Msg.SubmitVote
 */
export const MsgSubmitVoteService = {
  typeName: TYPE_NAME,
  method: "SubmitVote",
  Request: MsgSubmitVote,
  Response: MsgSubmitVoteResponse,
} as const;

/**
 * @generated from rpc pryzm.pgov.v1.Msg.SubmitProposal
 */
export const MsgSubmitProposalService = {
  typeName: TYPE_NAME,
  method: "SubmitProposal",
  Request: MsgSubmitProposal,
  Response: MsgSubmitProposalResponse,
} as const;

/**
 * this line is used by starport scaffolding # proto/tx/rpc
 *
 * @generated from rpc pryzm.pgov.v1.Msg.RetryVoteTransmit
 */
export const MsgRetryVoteTransmitService = {
  typeName: TYPE_NAME,
  method: "RetryVoteTransmit",
  Request: MsgRetryVoteTransmit,
  Response: MsgRetryVoteTransmitResponse,
} as const;

