// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file elys/tokenomics/tx.proto (package elys.tokenomics, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgClaimAirdrop, MsgClaimAirdropResponse, MsgCreateAirdrop, MsgCreateAirdropResponse, MsgCreateTimeBasedInflation, MsgCreateTimeBasedInflationResponse, MsgDeleteAirdrop, MsgDeleteAirdropResponse, MsgDeleteTimeBasedInflation, MsgDeleteTimeBasedInflationResponse, MsgUpdateAirdrop, MsgUpdateAirdropResponse, MsgUpdateGenesisInflation, MsgUpdateGenesisInflationResponse, MsgUpdateTimeBasedInflation, MsgUpdateTimeBasedInflationResponse } from "./tx_pb.js";

const TYPE_NAME = "elys.tokenomics.Msg";

/**
 * @generated from rpc elys.tokenomics.Msg.CreateAirdrop
 */
export const MsgCreateAirdropService = {
  typeName: TYPE_NAME,
  method: "CreateAirdrop",
  Request: MsgCreateAirdrop,
  Response: MsgCreateAirdropResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.UpdateAirdrop
 */
export const MsgUpdateAirdropService = {
  typeName: TYPE_NAME,
  method: "UpdateAirdrop",
  Request: MsgUpdateAirdrop,
  Response: MsgUpdateAirdropResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.DeleteAirdrop
 */
export const MsgDeleteAirdropService = {
  typeName: TYPE_NAME,
  method: "DeleteAirdrop",
  Request: MsgDeleteAirdrop,
  Response: MsgDeleteAirdropResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.ClaimAirdrop
 */
export const MsgClaimAirdropService = {
  typeName: TYPE_NAME,
  method: "ClaimAirdrop",
  Request: MsgClaimAirdrop,
  Response: MsgClaimAirdropResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.UpdateGenesisInflation
 */
export const MsgUpdateGenesisInflationService = {
  typeName: TYPE_NAME,
  method: "UpdateGenesisInflation",
  Request: MsgUpdateGenesisInflation,
  Response: MsgUpdateGenesisInflationResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.CreateTimeBasedInflation
 */
export const MsgCreateTimeBasedInflationService = {
  typeName: TYPE_NAME,
  method: "CreateTimeBasedInflation",
  Request: MsgCreateTimeBasedInflation,
  Response: MsgCreateTimeBasedInflationResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.UpdateTimeBasedInflation
 */
export const MsgUpdateTimeBasedInflationService = {
  typeName: TYPE_NAME,
  method: "UpdateTimeBasedInflation",
  Request: MsgUpdateTimeBasedInflation,
  Response: MsgUpdateTimeBasedInflationResponse,
} as const;

/**
 * @generated from rpc elys.tokenomics.Msg.DeleteTimeBasedInflation
 */
export const MsgDeleteTimeBasedInflationService = {
  typeName: TYPE_NAME,
  method: "DeleteTimeBasedInflation",
  Request: MsgDeleteTimeBasedInflation,
  Response: MsgDeleteTimeBasedInflationResponse,
} as const;

