// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file osmosis/poolincentives/v1beta1/query.proto (package osmosis.poolincentives.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryDistrInfoRequest, QueryDistrInfoResponse, QueryExternalIncentiveGaugesRequest, QueryExternalIncentiveGaugesResponse, QueryGaugeIdsRequest, QueryGaugeIdsResponse, QueryIncentivizedPoolsRequest, QueryIncentivizedPoolsResponse, QueryLockableDurationsRequest, QueryLockableDurationsResponse, QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";

const TYPE_NAME = "osmosis.poolincentives.v1beta1.Query";

/**
 * GaugeIds takes the pool id and returns the matching gauge ids and durations
 *
 * @generated from rpc osmosis.poolincentives.v1beta1.Query.GaugeIds
 */
export const QueryGaugeIdsService = {
  typeName: TYPE_NAME,
  method: "GaugeIds",
  Request: QueryGaugeIdsRequest,
  Response: QueryGaugeIdsResponse,
} as const;

/**
 * DistrInfo returns the pool's matching gauge ids and weights.
 *
 * @generated from rpc osmosis.poolincentives.v1beta1.Query.DistrInfo
 */
export const QueryDistrInfoService = {
  typeName: TYPE_NAME,
  method: "DistrInfo",
  Request: QueryDistrInfoRequest,
  Response: QueryDistrInfoResponse,
} as const;

/**
 * Params returns pool incentives params.
 *
 * @generated from rpc osmosis.poolincentives.v1beta1.Query.Params
 */
export const QueryParamsService = {
  typeName: TYPE_NAME,
  method: "Params",
  Request: QueryParamsRequest,
  Response: QueryParamsResponse,
} as const;

/**
 * LockableDurations returns lock durations for pools.
 *
 * @generated from rpc osmosis.poolincentives.v1beta1.Query.LockableDurations
 */
export const QueryLockableDurationsService = {
  typeName: TYPE_NAME,
  method: "LockableDurations",
  Request: QueryLockableDurationsRequest,
  Response: QueryLockableDurationsResponse,
} as const;

/**
 * IncentivizedPools returns currently incentivized pools
 *
 * @generated from rpc osmosis.poolincentives.v1beta1.Query.IncentivizedPools
 */
export const QueryIncentivizedPoolsService = {
  typeName: TYPE_NAME,
  method: "IncentivizedPools",
  Request: QueryIncentivizedPoolsRequest,
  Response: QueryIncentivizedPoolsResponse,
} as const;

/**
 * ExternalIncentiveGauges returns external incentive gauges.
 *
 * @generated from rpc osmosis.poolincentives.v1beta1.Query.ExternalIncentiveGauges
 */
export const QueryExternalIncentiveGaugesService = {
  typeName: TYPE_NAME,
  method: "ExternalIncentiveGauges",
  Request: QueryExternalIncentiveGaugesRequest,
  Response: QueryExternalIncentiveGaugesResponse,
} as const;

