// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file elys/tier/tx.proto (package elys.tier, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message elys.tier.MsgSetPortfolio
 */
export class MsgSetPortfolio extends Message<MsgSetPortfolio> {
  /**
   * @generated from field: string creator = 1;
   */
  creator = "";

  /**
   * @generated from field: string user = 2;
   */
  user = "";

  constructor(data?: PartialMessage<MsgSetPortfolio>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.tier.MsgSetPortfolio";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "creator", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSetPortfolio {
    return new MsgSetPortfolio().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSetPortfolio {
    return new MsgSetPortfolio().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSetPortfolio {
    return new MsgSetPortfolio().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSetPortfolio | PlainMessage<MsgSetPortfolio> | undefined, b: MsgSetPortfolio | PlainMessage<MsgSetPortfolio> | undefined): boolean {
    return proto3.util.equals(MsgSetPortfolio, a, b);
  }
}

/**
 * @generated from message elys.tier.MsgSetPortfolioResponse
 */
export class MsgSetPortfolioResponse extends Message<MsgSetPortfolioResponse> {
  constructor(data?: PartialMessage<MsgSetPortfolioResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "elys.tier.MsgSetPortfolioResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MsgSetPortfolioResponse {
    return new MsgSetPortfolioResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MsgSetPortfolioResponse {
    return new MsgSetPortfolioResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MsgSetPortfolioResponse {
    return new MsgSetPortfolioResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MsgSetPortfolioResponse | PlainMessage<MsgSetPortfolioResponse> | undefined, b: MsgSetPortfolioResponse | PlainMessage<MsgSetPortfolioResponse> | undefined): boolean {
    return proto3.util.equals(MsgSetPortfolioResponse, a, b);
  }
}

