// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file injective/auction/v1beta1/tx.proto (package injective.auction.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgBid, MsgBidResponse, MsgUpdateParams, MsgUpdateParamsResponse } from "./tx_pb.js";

const TYPE_NAME = "injective.auction.v1beta1.Msg";

/**
 * Bid defines a method for placing a bid for an auction
 *
 * @generated from rpc injective.auction.v1beta1.Msg.Bid
 */
export const MsgBidService = {
  typeName: TYPE_NAME,
  method: "Bid",
  Request: MsgBid,
  Response: MsgBidResponse,
} as const;

/**
 * @generated from rpc injective.auction.v1beta1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

