// @generated by protoc-gen-es v1.2.0 with parameter "target=ts"
// @generated from file refractedlabs/oracle/v1/genesis.proto (package refractedlabs.oracle.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Params } from "./params_pb.js";
import { FeederDelegation } from "./feeder_delegation_pb.js";
import { OraclePreVote } from "./oracle_pre_vote_pb.js";
import { OracleVote } from "./oracle_vote_pb.js";
import { MissCounter } from "./miss_counter_pb.js";

/**
 * GenesisState defines the oracle module's genesis state.
 *
 * @generated from message refractedlabs.oracle.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: refractedlabs.oracle.v1.Params params = 1;
   */
  params?: Params;

  /**
   * @generated from field: repeated refractedlabs.oracle.v1.FeederDelegation feeder_delegation_list = 2;
   */
  feederDelegationList: FeederDelegation[] = [];

  /**
   * @generated from field: repeated refractedlabs.oracle.v1.OraclePreVote oracle_pre_vote_list = 3;
   */
  oraclePreVoteList: OraclePreVote[] = [];

  /**
   * @generated from field: repeated refractedlabs.oracle.v1.OracleVote oracle_vote_list = 4;
   */
  oracleVoteList: OracleVote[] = [];

  /**
   * @generated from field: repeated refractedlabs.oracle.v1.MissCounter miss_counter_list = 5;
   */
  missCounterList: MissCounter[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "refractedlabs.oracle.v1.GenesisState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "params", kind: "message", T: Params },
    { no: 2, name: "feeder_delegation_list", kind: "message", T: FeederDelegation, repeated: true },
    { no: 3, name: "oracle_pre_vote_list", kind: "message", T: OraclePreVote, repeated: true },
    { no: 4, name: "oracle_vote_list", kind: "message", T: OracleVote, repeated: true },
    { no: 5, name: "miss_counter_list", kind: "message", T: MissCounter, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(a: GenesisState | PlainMessage<GenesisState> | undefined, b: GenesisState | PlainMessage<GenesisState> | undefined): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}

