// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file pryzm/ystaking/v1/tx.proto (package pryzm.ystaking.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgBond, MsgBondResponse, MsgClaimReward, MsgClaimRewardResponse, MsgExitPool, MsgExitPoolResponse, MsgUnbond, MsgUnbondResponse } from "./tx_pb.js";

const TYPE_NAME = "pryzm.ystaking.v1.Msg";

/**
 * @generated from rpc pryzm.ystaking.v1.Msg.Bond
 */
export const MsgBondService = {
  typeName: TYPE_NAME,
  method: "Bond",
  Request: MsgBond,
  Response: MsgBondResponse,
} as const;

/**
 * @generated from rpc pryzm.ystaking.v1.Msg.Unbond
 */
export const MsgUnbondService = {
  typeName: TYPE_NAME,
  method: "Unbond",
  Request: MsgUnbond,
  Response: MsgUnbondResponse,
} as const;

/**
 * @generated from rpc pryzm.ystaking.v1.Msg.ClaimReward
 */
export const MsgClaimRewardService = {
  typeName: TYPE_NAME,
  method: "ClaimReward",
  Request: MsgClaimReward,
  Response: MsgClaimRewardResponse,
} as const;

/**
 * this line is used by starport scaffolding # proto/tx/rpc
 *
 * @generated from rpc pryzm.ystaking.v1.Msg.ExitPool
 */
export const MsgExitPoolService = {
  typeName: TYPE_NAME,
  method: "ExitPool",
  Request: MsgExitPool,
  Response: MsgExitPoolResponse,
} as const;

