// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file cosmos/crisis/v1beta1/tx.proto (package cosmos.crisis.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgUpdateParams, MsgUpdateParamsResponse, MsgVerifyInvariant, MsgVerifyInvariantResponse } from "./tx_pb.js";

const TYPE_NAME = "cosmos.crisis.v1beta1.Msg";

/**
 * VerifyInvariant defines a method to verify a particular invariant.
 *
 * @generated from rpc cosmos.crisis.v1beta1.Msg.VerifyInvariant
 */
export const MsgVerifyInvariantService = {
  typeName: TYPE_NAME,
  method: "VerifyInvariant",
  Request: MsgVerifyInvariant,
  Response: MsgVerifyInvariantResponse,
} as const;

/**
 * UpdateParams defines a governance operation for updating the x/crisis module
 * parameters. The authority is defined in the keeper.
 *
 * Since: cosmos-sdk 0.47
 *
 * @generated from rpc cosmos.crisis.v1beta1.Msg.UpdateParams
 */
export const MsgUpdateParamsService = {
  typeName: TYPE_NAME,
  method: "UpdateParams",
  Request: MsgUpdateParams,
  Response: MsgUpdateParamsResponse,
} as const;

