// @generated by protoc-gen-cosmes v0.0.1 with parameter "target=ts"
// @generated from file cosmos/upgrade/v1beta1/query.proto (package cosmos.upgrade.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAppliedPlanRequest, QueryAppliedPlanResponse, QueryAuthorityRequest, QueryAuthorityResponse, QueryCurrentPlanRequest, QueryCurrentPlanResponse, QueryModuleVersionsRequest, QueryModuleVersionsResponse, QueryUpgradedConsensusStateRequest, QueryUpgradedConsensusStateResponse } from "./query_pb.js";

const TYPE_NAME = "cosmos.upgrade.v1beta1.Query";

/**
 * CurrentPlan queries the current upgrade plan.
 *
 * @generated from rpc cosmos.upgrade.v1beta1.Query.CurrentPlan
 */
export const QueryCurrentPlanService = {
  typeName: TYPE_NAME,
  method: "CurrentPlan",
  Request: QueryCurrentPlanRequest,
  Response: QueryCurrentPlanResponse,
} as const;

/**
 * AppliedPlan queries a previously applied upgrade plan by its name.
 *
 * @generated from rpc cosmos.upgrade.v1beta1.Query.AppliedPlan
 */
export const QueryAppliedPlanService = {
  typeName: TYPE_NAME,
  method: "AppliedPlan",
  Request: QueryAppliedPlanRequest,
  Response: QueryAppliedPlanResponse,
} as const;

/**
 * UpgradedConsensusState queries the consensus state that will serve
 * as a trusted kernel for the next version of this chain. It will only be
 * stored at the last height of this chain.
 * UpgradedConsensusState RPC not supported with legacy querier
 * This rpc is deprecated now that IBC has its own replacement
 * (https://github.com/cosmos/ibc-go/blob/2c880a22e9f9cc75f62b527ca94aa75ce1106001/proto/ibc/core/client/v1/query.proto#L54)
 *
 * @generated from rpc cosmos.upgrade.v1beta1.Query.UpgradedConsensusState
 * @deprecated
 */
export const QueryUpgradedConsensusStateService = {
  typeName: TYPE_NAME,
  method: "UpgradedConsensusState",
  Request: QueryUpgradedConsensusStateRequest,
  Response: QueryUpgradedConsensusStateResponse,
} as const;

/**
 * ModuleVersions queries the list of module versions from state.
 *
 * Since: cosmos-sdk 0.43
 *
 * @generated from rpc cosmos.upgrade.v1beta1.Query.ModuleVersions
 */
export const QueryModuleVersionsService = {
  typeName: TYPE_NAME,
  method: "ModuleVersions",
  Request: QueryModuleVersionsRequest,
  Response: QueryModuleVersionsResponse,
} as const;

/**
 * Returns the account with authority to conduct upgrades
 *
 * Since: cosmos-sdk 0.46
 *
 * @generated from rpc cosmos.upgrade.v1beta1.Query.Authority
 */
export const QueryAuthorityService = {
  typeName: TYPE_NAME,
  method: "Authority",
  Request: QueryAuthorityRequest,
  Response: QueryAuthorityResponse,
} as const;

